### ISSUE TITLE
Why do we need extra `scrollFunction()`?

### ISSUE THREAD

**Issue by ViolaPsch** [hypebright/scroll-to-top-shiny#1]
Hey Veerle,
thank you so much for your YouTube tutorial. It enabled me to build a scroll to top button to my shiny app which uses shinyglide (which didn't work with normal scroll to to top buttons). When reviewing again file [scrollPage.js](https://github.com/hypebright/scroll-to-top-shiny/blob/main/www/scrollPage.js) I was wondering if function `scrollFunction()` really is necessary or if we can directly do the check in `window.onscroll`? Like this:
```
window.onscroll = function() {
  if (document.documentElement.scrollTop > 20) || document.body.scrollTop > 20  { 
    document.getElementById("scroll-to-top-button").style.display = "block"
  } else {
    document.getElementById("scroll-to-top-button").style.display = "none"
  }
};
```

Thank you!
Viola

**Comment by hypebright** [comment]
@ViolaPsch, good question! And you're right, you don't necessarily need to create `scrollFunction()`. We could also rewrite it like so:

```
window.onscroll = () => {
  document.getElementById("scroll-to-top-button").style.display =
    document.body.scrollTop > 20 || document.documentElement.scrollTop > 20
      ? "block"
      : "none";
};
``` 

Even more concise by using a ternary operator and an arrow function 🙂. 

I'm going to add a comment on this in the `scrollPage.js` script and reference back to this issue.

**Comment by ViolaPsch** [comment]
Thank you for your update!
